### ISSUE TITLE
1.0.2 Support

### ISSUE THREAD

**Issue by mg3146** [lckr/jupyterlab-variableInspector#105]
Hi, this may be a simple question, but is there a way to install this for 1.0.2. JupyterLab?   I'm getting the following error when trying to install:

```
ValueError: This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.1 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/application
>=1.0.1 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/apputils
>=1.0.1 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/console
>=3.0.0 <4.0.0          >=2.1.4 <3.0.0 @jupyterlab/coreutils
>=1.0.1 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/notebook
>=4.0.1 <5.0.0          >=3.1.4 <4.0.0 @jupyterlab/services
See the log file for details:  c:\temp\jupyterlab-debug-6q8dwbbg.log
```

**Comment by maresb** [comment]
I was able to install to JupyterLab 1.0.2 by following the [instructions](https://github.com/lckr/jupyterlab-variableInspector#Installation) for cloning the repository from GitHub.  (Unfortunately I observed some strange behavior, for which I just opened an issue.)

**Comment by mg3146** [comment]
Great, thanks @maresb
