### ISSUE TITLE
What @jupyterlab/inspector is in relation to this

### ISSUE THREAD

**Issue by consideRatio** [lckr/jupyterlab-variableInspector#109]
I've been using this plugin, and sometimes plugin enter the JupyterLab official channel. I have now seen:
- https://www.npmjs.com/package/@jupyterlab/inspector
- https://www.npmjs.com/package/@jupyterlab/inspector-extension

The inspector package sais to be "A JupyterLab package which provides a variable inspector."

Is this extension related to that? I have not seen that in action yet and have failed to find more info about it.

**Comment by jtpio** [comment]
`@jupyterlab/inspector` is actually a contextual help, and the panel label was first renamed here: https://github.com/jupyterlab/jupyterlab/pull/6493 

![image](https://user-images.githubusercontent.com/591645/63787025-66dedb00-c8f3-11e9-9195-0f7d1a208886.png)

The description for `@jupyterlab/inspector` should probably be updated to reflect that.

**Comment by consideRatio** [comment]
Thanks for the insight @jtpio ! :heart:
