### ISSUE TITLE
Installation broke sidebar and tabs

### ISSUE THREAD

**Issue by MLBurnham** [lckr/jupyterlab-variableInspector#113]
Immediately after installation all of the default sidebar icons disappeared and some of the tabs encountered some graphical glitch.
Here's a shot of the blank sidebar as well as the glitched out tab:
![Screenshot from 2019-08-29 14-31-38](https://user-images.githubusercontent.com/41241150/63966943-5ef57700-ca6a-11e9-8e2a-07ae138cad5f.png)

When the I drag the tab around, this is what it looks like:

![Screenshot from 2019-08-29 14-31-54](https://user-images.githubusercontent.com/41241150/63966996-76346480-ca6a-11e9-847f-e91f78692957.png)

**Comment by MLBurnham** [comment]
To add, I was unable to fix the issue by disabling or un-installing the extension.  Opening Jupyter in core-mode is the only way I've found to fix this. I seem to be looking at a complete re-install

**Comment by MLBurnham** [comment]
Update: reinstalling Jupyter lab doesn't fix the issue. tried a complete reinstall of anaconda as well. Everything looks normal from a fresh install, but whenever I install any package I these errors pop up. This has basically rendered JupyterLab unusable.

**Comment by sho-87** [comment]
If this happens when you install any package (not just variable inspector), then its likely more likely to be a problem with jupyter/anaconda rather than this extension

after you install a package, what errors do you see in the terminal window that loaded jupyter lab? and what about errors in the chrome debugging console (F12)?

posting an issue in the jupyterlab repo might help you narrow the issue down quicker if its not isolated to just 1 extension

**Comment by MLBurnham** [comment]
Posted to the jupyterlab repo here: https://github.com/jupyterlab/jupyterlab/issues/7122

The issue initially arose after installing variable inspector, but I haven't been able to recreate in in a virtual environment. So you're probably right there's something else at play here.

**Comment by sho-87** [comment]
hopefully it gets resolved over there. will close this for now

**Comment by FlorianGD** [comment]
Hello,
I have the same issue. I had already installed another extension with no problem, but after installing this one, it somehow broke the jupyter lab build. I will follow the other issue, but just to let you know.

**Comment by FlorianGD** [comment]
And it was indeed coming from jupyterlab, fixed by updating to version 1.1.1
