### ISSUE TITLE
Don't do try: except for imports, check sys modules first

### ISSUE THREAD

**Issue by timkpaine** [lckr/jupyterlab-variableInspector#118]
You should check if the library is in `sys.modules` rather than try:excepting the imports. If the user has a `DataFrame` in their kernel, for example, then pandas will have already been imported. 

The issue with try:excepting arises when libraries like [tensorflow](https://github.com/lckr/jupyterlab-variableInspector/blob/master/src/inspectorscripts.ts#L44) are compiled with AVX, and run on machines without AVX. This will usually not raise an `ImportError`, but will instead cause a segfault leading to an infinite kernel restart loop. Again, if the user has a tf variable in their kernel, then tensorflow will have already imported fine and be in `sys.modules`. 
@vidartf @ceball

**Comment by vidartf** [comment]
> This will usually not raise an `ImportError`, but will instead cause a segfault

This does seem like an issue with tensorflow though 😞
