### ISSUE TITLE
Cannot view dataframe contents

### ISSUE THREAD

**Issue by RViking** [lckr/jupyterlab-variableInspector#121]
I was able to get the extension running, but when I click on a dataframe to view it's contents, it shows up empty (See below). The dataframe is populated, it is just not viewable for some reason. I suspect some other module/package/library etc. is not congruent with the extension.
 
![image](https://user-images.githubusercontent.com/35347325/68335752-1336fd80-00ab-11ea-8e90-9a020d0a49bd.png)

**Comment by xuzhou338** [comment]
Experienced the same issue... Waiting for a solution

**Comment by rtraghavan** [comment]
Me neither. I tried a fresh conda environment seeded with python3.7, nodejs, npm, numpy, pandas, and jupyterlab + the extension and had the same issue. That hopefully narrows down the problem.

**Comment by robscott95** [comment]
Same here - It won't even open a new window.

A side note: It opens up pd.Series objects just fine.

**Comment by stefanvangastel** [comment]
Same here.

**Comment by danaiz** [comment]
same here

**Comment by danaiz** [comment]
update here- after installing[]( https://ipywidgets.readthedocs.io/en/latest/user_install.html)
all works well
