### ISSUE TITLE
Publish a new release?

### ISSUE THREAD

**Issue by timkpaine** [lckr/jupyterlab-variableInspector#128]
Hey, thanks for being really responsive and merging all these PRs! Any chance you can push a new release up to npm? I'm really interested in 
https://github.com/lckr/jupyterlab-variableInspector/pull/125
and
https://github.com/lckr/jupyterlab-variableInspector/pull/119

**Comment by lckr** [comment]
Hey, I just published the current version to npm. I have to look into github actions s.t. the registry is updated automatically in the future.

If you encounter any problems let me know.

**Comment by timkpaine** [comment]
Awesome, thanks!
