### ISSUE TITLE
Successful installation but always empty 

### ISSUE THREAD

**Issue by ykm7788** [lckr/jupyterlab-variableInspector#135]
Hi, I think I probably have "successfully" installed and built this extension with the extension manager in jupyter lab since the `Varible Inspector` tab is visible. However, whatever I ran any code, `Varible Inspector` remains empty. 

So, I'm quite confused. Maybe its not caused by variableInspector itself, but is their any other issuses or conflicts I need to focus ?

I'm using windows10, python 3.8.2, Node.js v12.16.1., chrome 80.0.3987.132
 Jupyter lab environment :
```
jupyter core     : 4.6.3
jupyter-notebook : 6.0.3
qtconsole        : 4.7.2
ipython          : 7.13.0
ipykernel        : 5.2.0
jupyter client   : 6.1.1
jupyter lab      : 2.0.1
nbconvert        : 5.6.1
ipywidgets       : 7.5.1
nbformat         : 5.0.4
traitlets        : 4.3.3
```

Any way, thank you for developing this extension, should be quite useful !!

**Comment by lckr** [comment]
Related to #130
