### ISSUE TITLE
how to change kernel

### ISSUE THREAD

**Issue by yuGithuuub** [lckr/jupyterlab-variableInspector#138]
hi：
I am a newbie in python.
Thank you very much for your software to give Python a similar experience to Rstudio.
At work, I found that no matter which kernel I open, the original kernel is displayed, even if I have shut down it.
How to solve it

![image](https://user-images.githubusercontent.com/52593722/79051238-af1ff300-7c61-11ea-8d6d-2470e2234b64.png)

**Comment by zhtordinary** [comment]
I am faced with the same issue on Windows. My jupyterlab version is 2.1.0.

**Comment by RichardBoulet** [comment]
Same here
