### ISSUE TITLE
Object content is not displayed as widget

### ISSUE THREAD

**Issue by Robileo** [lckr/jupyterlab-variableInspector#140]
Thank you for this extension that looks very promising ! I encounter a problem though.

I can see all my variables but numpy arrays or matplotlib figures are displayed as strings (ex : 'Figure(432x288)'). Surprisingly, ipywidgets widgets I create are diplayed as widgets.
Did I forget something while installing ?

Here is my environment :
Os : Ubuntu 18.04.3 LTS

Jupyter :
```
conda list | grep jupy
jupyter                   1.0.0                    py37_7  
jupyter_client            5.3.4                    py37_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.1                    py37_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.0.6                      py_0 
```

```
jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: /home/leo/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @lckr/jupyterlab_variableinspector v0.4.0  enabled  OK
```
ipywidgets
```
conda list | grep ipywidgets
ipywidgets                7.5.1                      py_0 
```

**Comment by lckr** [comment]
Hey @Robileo, 
The inspector currently cannot display matplotlib figures. As you already experienced it can display ipython widgets. If you want to have your figures displayed in the inspector you have to use the `bqplot` library which outputs a figure as a ipython widget
