### ISSUE TITLE
Variable inspector doesn't launch (no option on right click)

### ISSUE THREAD

**Issue by sama2689** [lckr/jupyterlab-variableInspector#143]
I think I have installed it correctly onto Jupyterlab as it shows up under installed extensions but when I right click my notebook there is no option to open the variable inspector. Has anyone else had this issue? is there some way to enable it that I have missed?

**Comment by Robileo** [comment]
What `jupyter labextension list` gives you ?

**Comment by sama2689** [comment]
Known labextensions:
   app dir: C:\ProgramData\Anaconda3\envs\CondaEnvironment37\share\jupyter\lab
        @jupyter-widgets/jupyterlab-manager v1.1.0 enabled  ok
        @lckr/jupyterlab_variableinspector v0.4.0 enabled  ok

Uninstalled core extensions:
    @jupyter-widgets/jupyterlab-manager
    @lckr/jupyterlab_variableinspector
    @ryantam626/jupyterlab_code_formatter

> 
> 
> What `jupyter labextension list` gives you ?

**Comment by Robileo** [comment]
[This discussion](https://discourse.jupyter.org/t/extension-shows-up-as-both-installed-and-uninstalled-and-doesnt-work/2688) might help you. Try to delete anaconda3\share\jupyter\lab\settings\build_config.json and then rebuild jupyter lab.

**Comment by sama2689** [comment]
Unfortunately there is no settings folder under
anaconda3\share\jupyter\lab\

**Comment by byoung4** [comment]
I ran into this issue after uninstalling and then reinstalling jupyterlab-variableInspector. Once uninstalling it once, it would never show the option to open the variable inspector.

I was able to fix this by going into my ~/miniconda3/share/jupyter/lab/settings/build_config.json and deleting reference to @lckr/jupyterlab-variableInspector. I did that while JupyterLab was running, and it popped up a notification that said that the Variable Inspector should be added to build. After a rebuild (or manually via `$ jupyter lab build` it showed back up.

**Comment by MrUkulele** [comment]
> I ran into this issue after uninstalling and then reinstalling `jupyterlab-variableInspector`. Once uninstalling it once, it would never show the option to open the variable inspector after reinstall.
> 
> I was able to fix this by going into my `~/miniconda3/share/jupyter/lab/settings/build_config.json` and deleting the reference to `@lckr/jupyterlab-variableInspector`. I did that while JupyterLab was running, and it popped up a notification that said that the Variable Inspector should be added to build. After a rebuild (or manually via `$ jupyter lab build` it showed back up.

thank you soooooo much!!  you perfectly solve the problem!

**Comment by sama2689** [comment]
> 
> 
> I ran into this issue after uninstalling and then reinstalling `jupyterlab-variableInspector`. Once uninstalling it once, it would never show the option to open the variable inspector after reinstall.
> 
> I was able to fix this by going into my `~/miniconda3/share/jupyter/lab/settings/build_config.json` and deleting the reference to `@lckr/jupyterlab-variableInspector`. I did that while JupyterLab was running, and it popped up a notification that said that the Variable Inspector should be added to build. After a rebuild (or manually via `$ jupyter lab build` it showed back up.

Unfortunately when I went to /anaconda3/share/jupyter/lab/settings the folder was empty.

**Comment by byoung4** [comment]
@sama2689: When you type `jupyter labextension list` you'll get something like

```
JupyterLab v2.1.1
Known labextensions:
   app dir: /Users/$USER/miniconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v2.0.0  enabled  OK
        @jupyterlab/debugger v0.2.0  enabled  OK
        @jupyterlab/mathjax3-extension v3.0.0  enabled  OK
        @jupyterlab/toc v3.0.0  enabled  OK
        jupyterlab-execute-time v1.0.0  enabled  OK
        jupyterlab-theme-solarized-dark v1.0.1  enabled  OK

Uninstalled core extensions:
    @lckr/jupyterlab_variableinspector
```

If it says "*Uninstalled core extensions*" and the variable inspector is listed in there, then you have a `build_config.json` file somewhere that contains `@lckr/jupyterlab_variableinspector`.

Try doing
```bash
$ jupyter --paths
config:
    /Users/$USER/.jupyter
    /Users/$USER/miniconda3/etc/jupyter
    /usr/local/etc/jupyter
    /etc/jupyter
data:
    /Users/$USER/Library/Jupyter
    /Users/$USER/miniconda3/share/jupyter
    /usr/local/share/jupyter
    /usr/share/jupyter
runtime:
    /Users/$USER/Library/Jupyter/runtime
```

and search the `data` folders for `build_config.json`.

```bash
$ find /Users/$USER/Library/Jupyter -name build_config.json
$ find /Users/$USER/miniconda3/share/jupyter -name build_config.json
$ find /usr/local/share/jupyter -name build_config.json
$ find /usr/share/jupyter -name build_config.json
```
