### ISSUE TITLE
Variable inspector clears "tf" as a variable after cell run

### ISSUE THREAD

**Issue by ajyeager** [lckr/jupyterlab-variableInspector#145]
At first I thought this was a tensorflow problem, but later realized I can't store anything into a variable named "tf" without having it cleared.  This seems to only happen with variable-inspector is enabled.  See the simple 2-cell notebook below.  Notice how somewhere between running those two cells, tf got overwritten with None
![image](https://user-images.githubusercontent.com/11985639/82476802-90045480-9a9c-11ea-9309-7caa09bbc91a.png)

I'm using v0.5.0 of this plugin with jupyterlab 2.1.2

**Comment by paw-lu** [comment]
I've also been hit by this! Seems even when the extension is disabled this happens. See [#8493](https://github.com/jupyterlab/jupyterlab/issues/8493) for a gif and example. Also reported in [#8447](https://github.com/jupyterlab/jupyterlab/issues/8447).

**Comment by lckr** [comment]
See #147
