### ISSUE TITLE
How to open the extension after installation?

### ISSUE THREAD

**Issue by sidsidsidsid** [lckr/jupyterlab-variableInspector#148]
I'm not seeing where to open the extension. After installation via the Jupyter extension manager, there is nothing in any of the drop-downs that shows how to open. The demo alludes to the "edit" drop-down holds the item to select, but I do not see anything. 

1. Installed the extension via Jupyter lab extension manager.
2. Dialog box requested a rebuild.
3. Ran the below command and it appears the ext was installed. 
4. Stop/Started the Kernal
5. Stop/started Jupyter lab

__________________________________________________________________________________________-
(ve-env) C:\Users\xxx>jupyter labextension list
JupyterLab v2.1.3
Known labextensions:
   app dir: C:\Users\xxx\miniconda3\envs\vestv1\share\jupyter\lab
        @krassowski/jupyterlab-lsp v1.0.0 enabled  ok
        @lckr/jupyterlab_variableinspector v0.5.1 enabled  ok

**Comment by shervinsahba** [comment]
It's available in the context menu when you right-click a notebook. Or, `Ctrl+Shift+C` -> Search: Open Variable Explorer.

**Comment by teakfi** [comment]
I'm having same issue. And it is not available in the commands menu of JupyterLab v2.1.5. My guess is that it is related to newer Jupyter Lab versions.

**Comment by teakfi** [comment]
The issue is most likely in the jupyter lab itself. 

Removing the JSON-file mentioned here worked for me:
https://github.com/jupyterlab/jupyterlab/issues/8122

**Comment by canlang** [comment]
> The issue is most likely in the jupyter lab itself.
> 
> Removing the JSON-file mentioned here worked for me:
> [jupyterlab/jupyterlab#8122](https://github.com/jupyterlab/jupyterlab/issues/8122)

Thanks! (reboot was required in my case)
