### ISSUE TITLE
Variable Inspector should target Language Name instead of Kernel Name

### ISSUE THREAD

**Issue by chappers** [lckr/jupyterlab-variableInspector#15]
Right now kernels use the name instead of the language info. This could be called through:

```
session.kernel.info.language_info.name
```

instead of `session.kernel.name`.

However `kernel.info` can be null when `session.ready` promise is fulfilled. So one solution might be to check session.kernel.isReady and update the target language if that is changed(?)

There may be more appropriate patterns within session.kernel, however since kernel.name can be altered and user given, the variable explorer as it stands won't support multiple conda environments as an example.

I will think more on this and see if I can come up with a solution.

**Comment by lckr** [comment]
I'm reopening this since the `session.kernel` object can be null when it is called through `connector.ready`.
Reverting in #19.
We need to find some other solution

**Comment by chappers** [comment]
Hmm, 
When you revert it breaks all my conda envs :( 

But I you are right.

**Comment by lckr** [comment]
Possible solution in PR #23
