### ISSUE TITLE
'npm' is not recognized as internal or external command, operable program or batch file

### ISSUE THREAD

**Issue by YongpengZhao** [lckr/jupyterlab-variableInspector#150]
Hello guys! I've come up with a problem with installing. When I execute "npm install", an error was displayed in cmd, saying "'npm' is not recognized as internal or external command, operable program or batch file".

Has someone an idea, how it can be fixed?

Thank you all!

**Comment by zchelseal** [comment]
Have you [downloaded and installed Node.js](https://nodejs.org/en/download/)?
If you're seeing this from a Windows machine, it may be helpful to ensure that [Node.js is part of PATH in your environment variables](https://stackoverflow.com/questions/33055515/npm-is-not-recognized-as-an-internal-or-external-command-operable-program-or/33055592) 🙌

**Comment by YongpengZhao** [comment]
> Have you [downloaded and installed Node.js](https://nodejs.org/en/download/)?
> If you're seeing this from a Windows machine, it may be helpful to ensure that [Node.js is part of PATH in your environment variables](https://stackoverflow.com/questions/33055515/npm-is-not-recognized-as-an-internal-or-external-command-operable-program-or/33055592) 🙌

Thank you

**Comment by YongpengZhao** [comment]
> Have you [downloaded and installed Node.js](https://nodejs.org/en/download/)?
> If you're seeing this from a Windows machine, it may be helpful to ensure that [Node.js is part of PATH in your environment variables](https://stackoverflow.com/questions/33055515/npm-is-not-recognized-as-an-internal-or-external-command-operable-program-or/33055592) 🙌

Thank you!!!!!
