### ISSUE TITLE
Can't see "Open Variable Inspector" after installing the extension

### ISSUE THREAD

**Issue by islam-nassar** [lckr/jupyterlab-variableInspector#152]
I updated Jupyter lab to 2.1.4 from 1.2.6 to resolve this [issue](https://github.com/lckr/jupyterlab-variableInspector/issues/79). Once I did that, I can't access the variable inspector anymore through the right click. I reverted back to 1.2.6 but still the issue persists.

![image](https://user-images.githubusercontent.com/37215490/84609972-4a507580-aefc-11ea-8b75-62132af2edf7.png)

I really appreciate if you can help.

Here is my env: 
$ conda list | grep jupyter
jupyter                   1.0.0                    py37_7  
jupyter_client            6.1.3                      py_0  
jupyter_console           6.1.0                      py_0  
jupyter_core              4.6.3                    py37_0  
jupyterlab                1.2.6              pyhf63ae98_0  
jupyterlab_server         1.1.4                      py_0  

$ jupyter labextension list
JupyterLab v1.2.6
Known labextensions:
   app dir: /Users/inas0003/opt/anaconda3/share/jupyter/lab
        @jupyter-widgets/jupyterlab-manager v1.1.0  enabled  OK
        @jupyterlab/debugger v0.1.2  enabled  OK
        @lckr/jupyterlab_variableinspector v0.4.0  enabled  OK

Uninstalled core extensions:
    @lckr/jupyterlab_variableinspector

**Comment by teakfi** [comment]
I had same issue, this worked:

https://github.com/jupyterlab/jupyterlab/issues/8122
