### ISSUE TITLE
Issue with clicking and opening a variable 

### ISSUE THREAD

**Issue by deeppunj** [lckr/jupyterlab-variableInspector#153]
In Jupyter lab version 1.2.6, the variable inspector is having an issue with clicking and opening a variable. Wondering if it's only me or anyone else is facing the same issue. 

I can see a list of all the variables after opening the variable inspector in the Jupyter lab, but when I click on a variable name to open and see the values, it doesn't seem to respond at all. I have tries various work arounds but no luck. 

Thanks.

**Comment by ErwinSchleier** [comment]
Same here, I can open all variables except of the biggest one. On the attached picture it is called _feature_set_

![grafik](https://user-images.githubusercontent.com/33859933/85202817-5deb4a00-b309-11ea-9b69-09a81d630b33.png)

**Comment by hongwei94** [comment]
@ErwinSchleier can you  click on a variable name to open and see the full values? i can not click on a variable
