### ISSUE TITLE
Not showing/displaying current output variables/dataframes.  Also, not operational any longer

### ISSUE THREAD

**Issue by sidsidsidsid** [lckr/jupyterlab-variableInspector#159]
I love this plugin but seeing some issues and apparently not working for me any longer.

Step 1:
ran a *.py file code with certain variables and data frames. The plugin successfully displays current output variables.

Step 2:
made changes and created few new variables and data frames.

Step3:
ran "step 2", but "Step 1" variables and data frames appeared.

Step 4: 
attempted the following scenarios in order to fix the problem:
a. create a new console for the editor
b. restarted the kernel, closed python files, shutdown/restarted JupterLab and etc. It appears some caching is going on. I'm not sure if it's Python or the plugin. 
c. Note, when the plugin displayed the old output, clicking on one of the old data frames variables will not open it. It appears to be in some time of "read-only" mode
d. Tried uninstalled/re-installed the plugin. 

Step 5:
After attempting several shutdowns and re-installs, the plugin now does not appear in the drop-down dialog in order to start in a new tab. Also, after the last re-install, the plugin did not ask if I wanted a rebuild!!!

Any help would be appreciated.

**Comment by mcashm** [comment]
I am also seeing similar behavior. Most of the time, the right-click context menu opens a new tab with nothing in it.

**Comment by sidsidsidsid** [comment]
For my main problem; I found a workaround at the below link:
https://github.com/jupyterlab/jupyterlab/issues/8122

I have also seen the problem you have described. Unfortunately, the workaround didn't solve it. Only resolved my main problem. 

I'm still searching for a good Jupyterlab plugin that addresses debugging. I'm new to Jupyter and a little shock there are not many options in this space.

The below plugin sounded promising, but it requires "xeus-python 0.8.0+" ; which some of my 3rd party libraries do not support
https://github.com/jupyterlab/debugger
