### ISSUE TITLE
variables displayed as string variables if they are called "v"

### ISSUE THREAD

**Issue by matthias-k** [lckr/jupyterlab-variableInspector#16]
This seems to be a weird bug: When I execute

```python
a = 42
```

a is correctly displayed as variable of type `int` with value 42. However, when I execute

```python
v = 42
```

v is displayed as variable of type `str` with value `v`. The same happens if `v` is a bool variable or a string variable with some other value than `"v"`. Actually the demo in the README shows the same bug: https://github.com/lckr/jupyterlab-variableInspector/blob/master/early_demo.gif

**Comment by lckr** [comment]
Thank you guys for pointing this out.
