### ISSUE TITLE
Variable Inspector window remains empty 

### ISSUE THREAD

**Issue by braincharter** [lckr/jupyterlab-variableInspector#167]
Variable Inspector's extension seems to be enabled properly, but it remains empty..
![image](https://user-images.githubusercontent.com/35206039/96069256-cd161c80-0e6b-11eb-98dd-bfc72c85a1ea.png)

Here is the output of the installed labextensions:
```
JupyterLab v2.2.8
Known labextensions:
   app dir: C:\Users\berm2\anaconda3\envs\py37\share\jupyter\lab
        @aquirdturtle/collapsible_headings v2.2.0 enabled  ok
        @jupyter-widgets/jupyterlab-manager v2.0.0 enabled  ok
        @jupyterlab/git v0.22.1 enabled  ok
        @jupyterlab/hdf5 v0.4.1 enabled  ok
        @jupyterlab/toc v4.0.0 enabled  ok
        @krassowski/jupyterlab-lsp v2.0.7 disabled ok
        @lckr/jupyterlab_variableinspector v0.5.1 enabled  ok
        itkwidgets v0.32.0 enabled  ok
        jupyter-matplotlib v0.7.4 enabled  ok
        jupyterlab-datawidgets v6.3.0 enabled  ok
        jupyterlab-plotly v4.11.0 enabled  ok
        jupyterlab-system-monitor v0.6.0 enabled  ok
        jupyterlab-topbar-extension v0.5.0 enabled  ok
        jupyterlab_tensorboard v0.2.1 disabled ok
        nbdime-jupyterlab v2.0.1 enabled  ok

Uninstalled core extensions:
    @jupyterlab/google-drive
    @krassowski/jupyterlab-lsp
    jupyterlab_tensorboard
```

**Comment by jhconning** [comment]
I came here thinking that I was having the same experience.  However, after restarting the kernel on the notebook that I had open, the variable inspector did work.

**Comment by braincharter** [comment]
> I came here thinking that I was having the same experience. However, after restarting the kernel on the notebook that I had open, the variable inspector did work.

Sadly for me it didn't work. I even rebooted completely, made a new conda environment, etc. (I'm on windows). I did not try to downgrade my jupyter lab version though..

**Comment by Hongwei00** [comment]
@braincharter I have same problem,if u fixed it,please tell me.

**Comment by lckr** [comment]
Please check if this problem persists with the current version

**Comment by sourestdeeds** [comment]
I know this is closed, but I'm having this exact issue with the latest vscode and anaconda install. Did anyone come up with a solution?

**Comment by celestinoxp** [comment]
i have same problem. i have latest version of all packages
