### ISSUE TITLE
Varaible inspector doesn't open ndarrays

### ISSUE THREAD

**Issue by daelsh** [lckr/jupyterlab-variableInspector#169]
Hello,

I want to insect some ndarrays using the variable inspector.

When hovering over the ndarray name it sais 'View Contents'.

But klicking on it doesn't show anything.

Does anyone have any suggestions?

Thanks alot.

<img width="315" alt="Unbenannt" src="https://user-images.githubusercontent.com/70800902/96768502-305cfd00-13de-11eb-9d25-8638f7c7330a.PNG">

**Comment by lckr** [comment]
Should work in the current version
