### ISSUE TITLE
Does not work with Jupyter Lab 3

### ISSUE THREAD

**Issue by dpriedel** [lckr/jupyterlab-variableInspector#172]
Hi
This is a very useful extension but it doesn't work with the new version 3.0 of JupyterLab

The extension installs OK but when you right click in a cell to open the variable inspector an empty tab results. There are column headings but no variables are displayed. 
Also, clicking the close box on the tab does not work.

**Comment by FuriouslyCurious** [comment]
Seconded.  When I open VariableInspector in JupyterLab 3.0, I do not even get column headings - just a blank tab. 

The extension is enabled and listed in the extensions tab as active.

**Comment by okkymabruri** [comment]
Yeah, we are in the same problem. I will wait for the next upgrade

**Comment by nmweizi** [comment]
Yeah, we are in the same problem. I will wait for the next upgrade

**Comment by nmweizi** [comment]
I have same problem

**Comment by popcsev** [comment]
I also have the same issue with Jupyterlab 3.0.1 installed. Moreover, after clicking on the close button the variable ispector becomes blank and it does not close.

**Comment by jdtuck** [comment]
Same issues observed here

**Comment by M00NSH0T** [comment]
I also ran into this... should have checked here before trying, because now I'm unable to successfully get this working after rolling back to Jupyterlab 2. 

Have any of you tried installing this on a fresh install / environment?

I've always had issues getting this extension working after changing versions of Jupyterlab within a Conda environment. Uninstall / reinstall doesn't usually prompt you to rebuild even if you shut down the server after each step. Manual rebuild doesn't always bring back the 'Open Variable Inspector' option, and even when it does, it doesn't show anything or let you move it to another pane. In the past, like what I'm seeing now in Jupyterlab 3. Last time this happened (when I upgraded from jupyterlab 1 to 2) I had to go so far as to wipe my current conda environment and create a new one to get this extension working again. I haven't gone that far yet, but might be worth a shot.

**Comment by pfren1998** [comment]
I also encounter the same issue with Jupyterlab 3.0.3^^

**Comment by 2iyuye** [comment]
I also encountered the same problem, is there any solution?

**Comment by banshee7** [comment]
I'm having the same problem as well. I really got used to having this thing around so I'd love to see it get fixed.

**Comment by lckr** [comment]
Hey guys, I'm currently working on the migration to JLab 3.0, should be available later today.

**Comment by dpriedel** [comment]
Great....Thanks!!!!

**Comment by lckr** [comment]
The migration to 3.0 should be done now.  
**Note:** From now on the extension will be distributed via pip

If you run into any problems regarding the migration, please reopen.

**Comment by M00NSH0T** [comment]
ok I just tried installing this with pip and I hit an error. I've only ever used the extension manager within jupyter, however, so IDK if this is specific to this update or not. Also, I should point out, I'm doing this on my windows machine first... haven't tried on Linux yet, but wouldn't be surprised if perhaps this is windows specific. 


```  error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.1.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector': The system cannot find the path specified
  ----------------------------------------
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
Failed to build lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector which use PEP 517 and cannot be installed directly```

**Comment by M00NSH0T** [comment]
also, this was v3.0.1 and I see you've just released 3.0.2 in the past few minutes. pip doesn't recognize that new version yet... I'll try again shortly to see if that fixes the problem.

**Comment by dpriedel** [comment]
Installed on Linux and works fine.


Thanks


Dave R.

**Comment by rvillalba-novetta** [comment]
Will the new version be available in conda?

**Comment by lckr** [comment]
@M00NSH0T , I pushed some fixes that might solve your problem. Please try the new `v3.0.3` release and let me know if that works for you.

@rvillalba-novetta Good suggestion. I will look into it.

**Comment by dana-and-monsters** [comment]
Hi @lckr! Thanks for a great extension! I updated jupyter lab to 3.0.7 thinking that this would still work fine with this extension but the extension stopped working. I tried re-installing with pip and now I am getting the error "ERROR: Could not build wheels for lckr-jupyterlab-variableinspector which use PEP 517 and cannot be installed directly". Thank you so much for all of your help with this!

**Comment by M00NSH0T** [comment]
@dana-and-monsters did you try downgrading pip to 18.1?

**Comment by wbolton** [comment]
Hi, I had the same issue as @dana-and-monsters - tried downgrading pip and got:

`PS R:\Back Office\Analytics\Sand Box\Will B\Categorisation\Transactions Processing> pip install lckr-jupyterlab-variableinspector
Collecting lckr-jupyterlab-variableinspector
  Using cached https://files.pythonhosted.org/packages/f0/cb/cf109467b193ba9d9bb294795a34cacdbd57e9143985d073b512a99a4a57/lckr_jupyterlab_variableinspector-3.0.6.ta
r.gz
  Installing build dependencies ... error
  Complete output from command c:\users\will.bolton\anaconda3\python.exe -m pip install --ignore-installed --no-user --prefix C:\Users\Will.Bolton\AppData\Local\Tem
p\pip-build-env-pcpqxuey --no-warn-script-location --no-binary :none: --only-binary :none: -i https://pypi.org/simple -- jupyter_packaging~=0.7.9 jupyterlab>=3.0.0r
c13,==3.* setuptools>=40.8.0 wheel:
  Collecting jupyter_packaging~=0.7.9
    Using cached https://files.pythonhosted.org/packages/44/90/1ee67d0ca65bd507872accab7dfaad085ea9f9d74c7379b523dfd0498c0f/jupyter_packaging-0.7.12-py2.py3-none-an
y.whl
  Collecting jupyterlab==3.*,>=3.0.0rc13
    Using cached https://files.pythonhosted.org/packages/0a/55/d887557d1f6e3349d055384f96b33c7bd356571f35fb61856ace6c932b15/jupyterlab-3.1.0a3-py3-none-any.whl
  Collecting setuptools>=40.8.0
    Using cached https://files.pythonhosted.org/packages/70/06/849cc805ac6332210083f2114a95b22ee252ce81ed4e1be4f1d2b87c9108/setuptools-54.0.0-py3-none-any.whl
  Collecting wheel
    Using cached https://files.pythonhosted.org/packages/65/63/39d04c74222770ed1589c0eaba06c05891801219272420b40311cd60c880/wheel-0.36.2-py2.py3-none-any.whl
  Collecting packaging (from jupyter_packaging~=0.7.9)
    Using cached https://files.pythonhosted.org/packages/3e/89/7ea760b4daa42653ece2380531c90f64788d979110a2ab51049d92f408af/packaging-20.9-py2.py3-none-any.whl
  Collecting jinja2>=2.10 (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/7e/c2/1eece8c95ddbc9b1aeb64f5783a9e07a286de42191b7204d67b7496ddf35/Jinja2-2.11.3-py2.py3-none-any.whl
  Collecting jupyter-core (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/53/40/5af36bffa0af3ac71d3a6fc6709de10e4f6ff7c01745b8bc4715372189c9/jupyter_core-4.7.1-py3-none-any.whl
  Collecting tornado>=6.1.0 (from jupyterlab==3.*,>=3.0.0rc13)
    Downloading https://files.pythonhosted.org/packages/cf/44/cc9590db23758ee7906d40cacff06c02a21c2a6166602e095a56cbf2f6f6/tornado-6.1.tar.gz (497kB)
  Collecting jupyterlab-server~=2.2 (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/dd/a7/fd7f7e38647b3c1d8ae37bf8b21157662d84ebd0ebf5b64a607c7c77f676/jupyterlab_server-2.3.0-py3-none-any.whl

  Collecting ipython (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/3b/43/6dbd0610550708fc418ad027fda97b5f415da9053749641654fdacfec93f/ipython-7.21.0-py3-none-any.whl
  Collecting nbclassic~=0.2 (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/e6/f0/113b9a6975e53285c56091a250be4828dd20d80172620a4ff74ed26c9fe7/nbclassic-0.2.6-py3-none-any.whl
  Collecting jupyter-server~=1.2 (from jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/ec/b7/f8964ca33e61c6fa8f4e494e4940fb6de021f5caa52c2dce32316fac8611/jupyter_server-1.4.1-py3-none-any.whl
  Collecting pyparsing>=2.0.2 (from packaging->jupyter_packaging~=0.7.9)
    Using cached https://files.pythonhosted.org/packages/8a/bb/488841f56197b13700afd5658fc279a2025a39e22449b7cf29864669b15d/pyparsing-2.4.7-py2.py3-none-any.whl
  Collecting MarkupSafe>=0.23 (from jinja2>=2.10->jupyterlab==3.*,>=3.0.0rc13)
    Downloading https://files.pythonhosted.org/packages/b9/2e/64db92e53b86efccfaea71321f597fa2e1b2bd3853d8ce658568f7a13094/MarkupSafe-1.1.1.tar.gz
  Collecting traitlets (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13)
    Using cached https://files.pythonhosted.org/packages/f6/7d/3ecb0ebd0ce8dcdfa7bd47ab85c1d4a521e6770ef283d0824f5804994dfe/traitlets-5.0.5-py3-none-any.whl
  Collecting pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13)
    Could not find a version that satisfies the requirement pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13) (from versions: )

  No matching distribution found for pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13)
  You are using pip version 18.1, however version 21.0.1 is available.`

**Comment by wbolton** [comment]
Hi, I had the same issue as @dana-and-monsters - tried downgrading pip and got:

`  Collecting pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13)
    Could not find a version that satisfies the requirement pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13) (from versions: )

  No matching distribution found for pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13)
  You are using pip version 18.1, however version 21.0.1 is available.
  You should consider upgrading via the 'python -m pip install --upgrade pip' command.`

**Comment by miGa77** [comment]
For me the same issue as @dana-and-monsters and @wbolton .
Spent the whole day to get this working, but haven't found a solution.

` error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector': Das System kann den angegebenen Pfad nicht finden`

Before I had same error messages like 
`ERROR: Could not build wheels for lckr-jupyterlab-variableinspector which use PEP 517 and cannot be installed directly` and `Could not find a version that satisfies the requirement pywin32>=1.0; sys_platform == "win32" (from jupyter-core->jupyterlab==3.*,>=3.0.0rc13) (from versions: )
`.

**Comment by lckr** [comment]
You can now also obtain/install the extension from npm again, this could circumvent these path issues that happen on windows.
Please refer to the installation instructions in the readme.

**Comment by s36203** [comment]
Still no luck for me. On jupyter 3.0. Tried both pip and npm.

**Comment by Lilac-in-April** [comment]
still not working. I got this:
```
note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
Failed to build lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector, which is required to install pyproject.toml-based projects
```
