### ISSUE TITLE
Supporting other Python Frameworks Gracefully in Matrix Display

### ISSUE THREAD

**Issue by chappers** [lckr/jupyterlab-variableInspector#18]
**Proposed Patterns**

This is to talk through support for other frameworks, and possible ways to handle it safely

- [x] Spark
- [x] Tensorflow

One approach which I've demo'ed is to use `pd.get_options` to control spark dataframes when pulling datasets through 

`spark_df.limit(<number>).toPandas()`

For tensorflow variables you will inevitably pulling full matrices down.

**Displaying Pandas and Numpy**

One option for handling the display of data is to limit it to:

```
max(10**6, pd.get_option('display.max_rows')) if pd.get_option('display.max_rows') is not None else <show all>
```

We can do the same thing for the `numpy` equivalent. This should naturally flow-on to the default Pandas + Numpy variables.

**Handling Imports**

Using the approach shown in the [Rodeo variable explorer](https://github.com/yhat/rodeo/blob/0b4a9ed5acf052fa9e2eca9427263b5dc44c187d/src/node/kernels/python/langs/python-patch.py) I think the pattern for handling unknown imports (not everyone will have tensorflow/pyspark or even pandas installed):

```py
try:
    import my_module
except ImportError:
    my_module = None

....

if my_module and isinstance(x, my_module.my_type):
    <do stuff>
```

If @lckr agrees, I'll ensure my PRs are aligned and cleaned up for review.

**Comment by lckr** [comment]
I like your proposal and I'm looking forward to review your PR.

**Comment by lckr** [comment]
@chappers Does this issue need more work or would you consider it done?

**Comment by chappers** [comment]
I'll consider it done for now. New issues can be opened if others want support
