### ISSUE TITLE
issue with latest version (3.0.2) in Windows

### ISSUE THREAD

**Issue by M00NSH0T** [lckr/jupyterlab-variableInspector#181]
first of all, thank you for making this extension. It's incredibly useful.

Anyway, when I installed earlier versions of this via the extension manager within Jupyter Lab, it worked as intended. However, the latest version (3.0.2) appears to require installation via pip instead, which, after downgrading to pip 18.1 (see [here](https://github.com/lckr/jupyterlab-variableInspector/issues/172#issuecomment-761177372)), results in the variable inspector window installing and activating correctly, but it never updates to actually show any variables. Unlike other bugs I've encountered with upgrading to new versions of jlab before the extension had been upgraded, I am able to move the variable instpector window around to new panes. It's responsive and appears to not be frozen (like it will show "restarting kernel" if I restart a kernel), but it never lists active variables in my notebooks.

**Comment by lckr** [comment]
Hey, I could not reproduce this issue on linux using a python kernel. 
If you're also using a py kernel try to execute `_jupyterlab_variableinspector_dict_list()` in a notebook with an existing variable to check if the extension scripts have been pushed successfully to the kernel.

**Comment by M00NSH0T** [comment]
you mean just run `_jupyterlab_variableinspector_dict_list()` in a cell in an active workbook?

if so, I get the following error:
```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-22-a2d401806d89> in <module>
----> 1 _jupyterlab_variableinspector_dict_list()

NameError: name '_jupyterlab_variableinspector_dict_list' is not defined
```

**Comment by lckr** [comment]
Please try the new `3.0.3` release which should fix this issue.

**Comment by M00NSH0T** [comment]
confirmed that's working. Thank you very much!
