### ISSUE TITLE
3.02 doesn't show variables

### ISSUE THREAD

**Issue by discdiver** [lckr/jupyterlab-variableInspector#182]
Installed 3.02 into my conda environment via pip on my mac.

    lckr-jupyterlab-variableinspector 3.0.2                    pypi_0    pypi

Uninstalled jupyterlab extension. Rebuilt extensions and restarted jupyter lab (installed latest version of jupyter lab today and upgraded node).

Now I don't see variables, although the variable inspector fires up just fine. 

Thank you for this extension!

**Comment by lckr** [comment]
Hey, can you try to execute `_jupyterlab_variableinspector_dict_list()` in a notebook with an existing variable to confirm that the extension code was successfully pushed to the notebook kernel?

**Comment by discdiver** [comment]
result of running `jupyterlab_variableinspector_dict_list()` in a notebook with many variables in memory:

```
---------------------------------------------------------------------------
NameError                                 Traceback (most recent call last)
<ipython-input-345-a2d401806d89> in <module>
----> 1 _jupyterlab_variableinspector_dict_list()

NameError: name '_jupyterlab_variableinspector_dict_list' is not defined
```

**Comment by dpriedel** [comment]
I can confirm that 3.0.2 does not show variables on Linux either.

3.0.1 DOES work however.

**Comment by lckr** [comment]
> I can confirm that 3.0.2 does not show variables on Linux either.
> 
> 3.0.1 DOES work however.

Thats strange. For me the following works with `jupyterlab = 3.0.5` on firefox.

```bash
conda create -n "variable_inspector"
conda activate variable_inspector
conda install -c conda-forge jupyterlab
pip install -U lckr-jupyterlab-variableinspector
```
Is your setup any different?

**Comment by dpriedel** [comment]
I am running on Linux with my python install in /usr/local/python-3.9. I 
have the latest jupyterlab installed.

I launch jupyter as follows:


PATH=/usr/local/python-3.9/bin:$Path jupyter lab --notebook-dir=/<path 
to notebooks>

Everything works with 3.0.1 but 3.0.2 just shows me an empty window with 
column titles.

**Comment by lckr** [comment]
Hi, I think I found the bug: Some white space changes corrupted the scripts that need to pushed to the kernel s.t. the extension can work.
I pushed the changes to master and deployed a new release (v3.0.3). Please try this one and let me know if that works for you.

**Comment by dpriedel** [comment]
Hi


Installed the 3.0.4 update and all works again.


Thanks !!


Dave R


PS.  I don't remember whether or not this is a change but when I click 
on the magnifying glass to expand a dataframe, for example, the tab 
which opens up does not respond to keyboard navigation, such as 
page-down, the way the main variable watcher window does. I can only use 
the scroll bar.
