### ISSUE TITLE
Jupyter Lab 3.0.7 Not working with Variable Inspector

### ISSUE THREAD

**Issue by dana-and-monsters** [lckr/jupyterlab-variableInspector#193]
Hi! I love this extension! It was working well with Jupyter Lab 2. something but since updating Jupyter lab now I cannot see variables and I cannot exit the variable inspector either. I also cannot dock it on the right side of the screen. I am wondering if this could be a local issue as I had a lot of trouble updating to Jupyter Lab 3 with Anaconda. 

![image](https://user-images.githubusercontent.com/30321989/107203216-72e12e80-69fb-11eb-8386-b510d6bd7016.png)

**Comment by lckr** [comment]
Hey, the version on npm is currently outdated. In the meantime, you can obtain the current version via `pip install lckr-jupyterlab-variableinspector`.
