### ISSUE TITLE
Unable to start Variable explorer 

### ISSUE THREAD

**Issue by s36203** [lckr/jupyterlab-variableInspector#196]
I am not able to see variable explorer on jupyterlab and I checked the lab extension list and it says enabled

![image](https://user-images.githubusercontent.com/7207527/107528616-08112e00-6b88-11eb-91f6-ce07cefa9444.png)

**Comment by dkinneyBU** [comment]
I am having the same issue. Could be coincidence, but I also just recently upgraded Jupyter Lab to 2.2.6. When I did that, a number of my extensions stopped working and/or generated error messages.

**Comment by xamevou** [comment]
Same problem here.

**Comment by dkinneyBU** [comment]
Soooo, I guess no one cares. I'm going to assume this is not being maintained any more given that there has been no response other than crickets.

**Comment by s36203** [comment]
Looks like it

**Comment by lckr** [comment]
Hey guys, this extension only supports Jupyterlab >= 3.0.0 since a few months ago. please try upgrading the extension (preferable via pip).
Since some of you seem to need to install from npm, I will now deploy new versions of the package to the npm-registry again.
