### ISSUE TITLE
Absolute Path

### ISSUE THREAD

**Issue by anthonytec2** [lckr/jupyterlab-variableInspector#2]
Awesome job on the extension this should be really useful😊! Just one note, I tried to configure the path to var_list.py using an absolute path, although I had no luck with this approach. I was finally able to get it to work by specifying the path relative to whatever current working directory I am running jupyter lab. Maybe, I am just configuring the path wrong but I just wanted to make this note.

**Comment by lckr** [comment]
No, you're right. All paths have to be relative to the root directory of the jupyter lab instance. I changed the loading of the scripts in the _betterScriptloading_ branch, s.t. it does not rely on any external files.
