### ISSUE TITLE
Cannot Install

### ISSUE THREAD

**Issue by dongwoo-92** [lckr/jupyterlab-variableInspector#201]
Thanks a lot for nice extension.

I want to install this extension, however, it doesn't work with following errors.
Can I have a some opinion to fix this problem?

    1) I write down 'pip install lckr-jupyterlab-variableinspector' in my conda envs with CUI
    2) I have error message as below marked [ERROR MESSAGE] (sorry for quite long)
    3) I have no idea what's the problem. Please let me know how can I fix it.

[ERROR MESSAGE]
Building wheels for collected packages: lckr-jupyterlab-variableinspector
  Building wheel for lckr-jupyterlab-variableinspector (PEP 517) ... error
  ERROR: Command errored out with exit status 1:
   command: 'c:\programdata\anaconda3\envs\dum2\python.exe' 'c:\programdata\anaconda3\envs\dum2\lib\site-packages\pip\_vendor\pep517\_in_process.py' build_wheel 'C:\Users\toaeh\AppData\Local\Temp\tmpx6si4v_g'
       cwd: C:\Users\toaeh\AppData\Local\Temp\pip-install-jy948g0_\lckr-jupyterlab-variableinspector_a6733900534b4ce381cf0263386d3b9b
  Complete output (50 lines):
  running bdist_wheel
  running jsdeps
  running handle_files
  running build
  running build_py
  creating build
  creating build\lib
  creating build\lib\lckr_jupyterlab_variableinspector
  copying lckr_jupyterlab_variableinspector\_version.py -> build\lib\lckr_jupyterlab_variableinspector
  copying lckr_jupyterlab_variableinspector\__init__.py -> build\lib\lckr_jupyterlab_variableinspector
  running egg_info
  writing lckr_jupyterlab_variableinspector.egg-info\PKG-INFO
  writing dependency_links to lckr_jupyterlab_variableinspector.egg-info\dependency_links.txt
  writing requirements to lckr_jupyterlab_variableinspector.egg-info\requires.txt
  writing top-level names to lckr_jupyterlab_variableinspector.egg-info\top_level.txt
  reading manifest file 'lckr_jupyterlab_variableinspector.egg-info\SOURCES.txt'
  writing manifest file 'lckr_jupyterlab_variableinspector.egg-info\SOURCES.txt'
  creating build\lib\lckr_jupyterlab_variableinspector\labextension
  copying lckr_jupyterlab_variableinspector\labextension\package.json -> build\lib\lckr_jupyterlab_variableinspector\labextension
  creating build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\383.7b9187c38867b5826721.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\453.8c3e228b049bcae471dc.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\534.879f22f7b76b38ac76c6.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\remoteEntry.21f70e62a0abee7edc80.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  copying lckr_jupyterlab_variableinspector\labextension\static\style.js -> build\lib\lckr_jupyterlab_variableinspector\labextension\static
  installing to build\bdist.win-amd64\wheel
  running install
  running install_lib
  creating build\bdist.win-amd64
  creating build\bdist.win-amd64\wheel
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector\labextension
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\package.json -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\383.7b9187c38867b5826721.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\453.8c3e228b049bcae471dc.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\534.879f22f7b76b38ac76c6.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\remoteEntry.21f70e62a0abee7edc80.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\labextension\static\style.js -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector\labextension\static
  copying build\lib\lckr_jupyterlab_variableinspector\_version.py -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector
  copying build\lib\lckr_jupyterlab_variableinspector\__init__.py -> build\bdist.win-amd64\wheel\.\lckr_jupyterlab_variableinspector
  running install_data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter\labextensions
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter\labextensions\@lckr
  creating build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector
  error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.6.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector': The system cannot find the path specified
  ----------------------------------------
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
Failed to build lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector which use PEP 517 and cannot be installed directly

**Comment by Amir-Abi** [comment]
I also got this error and don't know what it means .

**Comment by darribas** [comment]
I'm experiencing the same issue, any suggestions on how to work around it?

**Comment by lckr** [comment]
Sound like a windows issue, please try using a different installation approach (see README.md)
