### ISSUE TITLE
I can't see variable Inspector the menu

### ISSUE THREAD

**Issue by Kim-Byung-woo** [lckr/jupyterlab-variableInspector#203]
I installed variable Inspector using manager.
I right clicked and the inspector menu is not showing.
Teach me how to solve it

![inspector error](https://user-images.githubusercontent.com/36158353/113847919-e670a380-97d2-11eb-9c72-2b2b6337e17d.jpg)

**Comment by gi3265** [comment]
I have the exact problem too

**Comment by lckr** [comment]
Could not reproduce this issue. Note, that the installation via the Jupyterlab built-in extension manager was broken but should be working now again. Please make sure your working with Jupyterlab >= 3.0.0 and jupyterlab-variableinspector >= 3.0.9

**Comment by gi3265** [comment]
I've double checked the required versions in order to run the extension properly(Jupyterlab >= 3.0.11 and jupyterlab-variableinspector = 3.0.9). Didn't worked out so I downgraded jupyterlab to 3.0.6.
Still the inspector menu won't show when i click the right button.
Any suggestion would be appreciated.

**Comment by gi3265** [comment]
> I installed variable Inspector using manager.
> I right clicked and the inspector menu is not showing.
> Teach me how to solve it
> 
> ![inspector error](https://user-images.githubusercontent.com/36158353/113847919-e670a380-97d2-11eb-9c72-2b2b6337e17d.jpg)

#183  여기 가장 하단의 방법 참고해서 pip로 install해 보세요! 전 그렇게 설치하니 해결됐습니다

**Comment by Kim-Byung-woo** [comment]
The problem was solved by following the method you taught. Thank you.
