### ISSUE TITLE
fails to install - build errors on jupyter lab build on windows 10

### ISSUE THREAD

**Issue by jj-github-jj** [lckr/jupyterlab-variableInspector#236]
Get this error.  
![image](https://user-images.githubusercontent.com/79281080/149848268-510b9b47-39a6-44b2-9bad-aba053059507.png)

**Comment by m-d-grunnill** [comment]
I have the same issue.

**Comment by imcovangent** [comment]
I also have the same issue.

**Comment by Shang-LM** [comment]
Same error on windows 11

**Comment by lckr** [comment]
This is a issue related to windows paths and has been discussed in other issues.
