### ISSUE TITLE
fails to build on windows 10 , jupyter lab 3.2.8, python 3.9.1

### ISSUE THREAD

**Issue by jj-github-jj** [lckr/jupyterlab-variableInspector#238]
get this error pretty frequently whenever i  try to setup variable inspector on a new machine 
![image](https://user-images.githubusercontent.com/79281080/151717186-50e4dc9d-edb0-463f-8fbb-3cbcbc1d7281.png)

But found that downloading  and renaming to a shorter name and installing from the local directory worked 
Step 1: Download the [tar.gz](https://github.com/lckr/jupyterlab-variableInspector/archive/refs/tags/v3.0.6.tar.gz) file from release page to a short path, ie "C:\mypy", and rename the tar.gz file to a short file name, ie "vi.tar.gz" (not necessary maybe?)
Step 2: run CMD, type the following in command shell
  C:\mypy\pip install vi.tar.gz

**Comment by rnd195** [comment]
I had the same issue while trying to install the package through the extension manager. I then tried using `pip` to get the package by running `pip install lckr-jupyterlab-variableinspector`, which ended up working for me.

Alternatively, if you're using conda, consider looking at [this](https://github.com/lckr/jupyterlab-variableInspector/issues/237#issuecomment-1050987641) answer in issue #237.

**Comment by lckr** [comment]
This is a common windows issue with long paths. Glad you could find an alternative way of installing the extension
