### ISSUE TITLE
Install Error

### ISSUE THREAD

**Issue by parxkbrand** [lckr/jupyterlab-variableInspector#242]
I have been trying to install this for several days to no avail.  This is my latest error, I already tried to downgrade pip to 18.1 and install variable inspector but it did not work.

Any help would be greatly appreciated.

 error: could not create 'build\bdist.win-amd64\wheel\lckr_jupyterlab_variableinspector-3.0.9.data\data\share\jupyter\labextensions\@lckr\jupyterlab_variableinspector': The system cannot find the path specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lckr-jupyterlab-variableinspector
Failed to build lckr-jupyterlab-variableinspector
ERROR: Could not build wheels for lckr-jupyterlab-variableinspector, which is required to install pyproject.toml-based projects

**Comment by bitcoffe** [comment]
if you use `conda` ， you can use `conda install jupyterlab-variableinspector `

**Comment by VirginieSonnet** [comment]
In case you don't use conda, downloading the tar file, changing the name to a shorter one, installing it with pip and enabling the extension( `jupyter labextension enable @lckr/jupyterlab_variableinspector`) did work for me. The solution come from here: https://github.com/lckr/jupyterlab-variableInspector/issues/207#issuecomment-847530435
