### ISSUE TITLE
pip install doesn't respect constraints file

### ISSUE THREAD

**Issue by jrowen** [lckr/jupyterlab-variableInspector#250]
I'm trying to use a pip constraints file to pin the notebook dependency to v6.4.11, and I'm running into an error.  The command is:

    pip install lckr-jupyterlab-variableinspector -c constraints.txt

And the constraints file includes:

    notebook<=6.4.11

Since the installation of notebook v6.4.12 is blocked in my environment, I continue to see the error below:
```
 ERROR: Could not install requirement notebook<7
  note: This error originates from a subprocess, and is likely not a problem with pip.
error: subprocess-exited-with-error
```
It appears that the pip installation process is not passing all of configuration settings to the subprocess that installs the Python dependencies.

**Comment by lckr** [comment]
This extension does not depend on `notebook` directly but only indirectly via `jupyterlab >= 3`.
I'm not sure whether `jupyterlab >= 3 && notebook <= 6.4.11` is resolvable.
And regarding passing dependency constraints during `pip install` to subprocesses please check with `pip`
