### ISSUE TITLE
Add a title element to show what kernel we're in?

### ISSUE THREAD

**Issue by chappers** [lckr/jupyterlab-variableInspector#26]
This should be easy to do. 
Add something to `variableinspector.ts` to show the title/name of the kernel, perhaps language etc?

This is shown by @kazuar in the demo here: https://github.com/jupyterlab/jupyterlab/issues/443

_Question_

*  How "important" is this feature? Do we actually need it?

**Comment by lckr** [comment]
I think that's a great idea and especially helpful when dealing with multiple notebooks in a "tiling" view.
Additionally, it should be quite easy to implement.
Generally, I think we can improve on the visual representation of the inspector such as fixing the color change of the table header.

This also got me thinking whether there is a situation where one would need to inspect multiple notebooks at once, i.e., show the variables in two inspector windows for two kernels.
Do you can think of such a situation?

**Comment by chappers** [comment]
re: multiple notebooks/variables - I think I've seen something like that referenced in the [sos project](https://vatlab.github.io/sos-docs/) as it mixes multiple languages in a single notebook, but in general I don't see a situation for it...

**Comment by chappers** [comment]
On the changing colours I'm all for it, so long as the user can toggle it on and off, can definitely imagine certain people hating it.

We might also want colours tied to the variable types in the table like Spyder...might be a separate card

**Comment by lckr** [comment]
Regarding the visual presentation it might be the best if we stick as close as possible to the jupyterlab design. Currently the explorer looks somewhat clunky to me. I'm going to research if there are general style or design guidelines from the jupyterteam that we can use.

I didn't use spyder yet, can you provide some resources about their color scheme?

**Comment by chappers** [comment]
Sure it looks something like this:

![image](https://user-images.githubusercontent.com/2498638/42567664-d2934ace-854d-11e8-980a-d97e79bd505c.png)

Things of the same data type have the same background

**Comment by lckr** [comment]
Are the colors for integers and string the same as for floats? In general, I think such a color coding might be helpful but on the other hand it doesn't fit the Jupyter visuals very good.
We might want to make it optional or try to find a more appropriate color encoding.

**Comment by chappers** [comment]
Yeah that's fine it's more of a nice to have

**Comment by chappers** [comment]
Let's close this. We can add a different issue for colours if people are after it.
