### ISSUE TITLE
TODOs before beta release

### ISSUE THREAD

**Issue by lckr** [lckr/jupyterlab-variableInspector#28]
Things to add before a first release. (In no specific order)
- [x] Improve styling
- [x] Installation via npm
- [ ] Improve UX
- [ ] Add documentation

optional:
- [ ] Make inspector table sortable
- [ ] Add option to set max_rows
- [x] Add R support

**Comment by lckr** [comment]
@chappers Do you know any lightweight library we might use to allow a sortable table?

**Comment by chappers** [comment]
I do not sorry :(

**Comment by davidolmo** [comment]
You guys are doing superb work! I know a lot of people who is waiting for this to come. Everyone in the data science space will be using this :) 
thanks!

**Comment by sho-87** [comment]
@lckr  I used to use DataTables (jquery) for sorting tables. not sure if its too heavy for this purpose but its quite flexible: https://datatables.net/
