### ISSUE TITLE
Inspector does not reload variables upon kernel restart

### ISSUE THREAD

**Issue by lmtsui** [lckr/jupyterlab-variableInspector#38]
When I press 00 to restart kernel, the variables listed in the inspector did not refresh. It got stuck in the previous kernel and did not respond to variable updates in the new kernel.

**Comment by lckr** [comment]
Thanks for your report @lmtsui. I will look into it in the next days.

**Comment by saravanabalagi** [comment]
I'm still getting this error, I'm not able to use the variable inspector except for the first time for any notebook

![image](https://user-images.githubusercontent.com/8567893/67005829-713f7900-f0db-11e9-9d9d-2f6980ec661d.png)

**Comment by lckr** [comment]
What jupyterlab and variableInspector version are you using?

**Comment by AlcoholV** [comment]
@lckr 
I have a same issue.
I'm using  @lckr/jupyterlab_variableinspector v0.3.0.

**Comment by ceen1** [comment]
I have the same problem
