### ISSUE TITLE
Index cells is empty

### ISSUE THREAD

**Issue by MohHizzani** [lckr/jupyterlab-variableInspector#40]
When using pandas dataframe, with multi-index index in variable inspector is empty

![screenshot from 2018-08-29 13-39-51](https://user-images.githubusercontent.com/30414163/44782910-6b15d280-ab91-11e8-91f6-7d89603c8ba1.png)

**Comment by lckr** [comment]
Hey @MohHizzani , 
thanks for your report. This is fixed in #46. Please note that it is not possible to view dataframes with multiindexed columns. For more details refer to the mentioned PR.
