### ISSUE TITLE
Cannot install - Version incompatibility 

### ISSUE THREAD

**Issue by ajscriv** [lckr/jupyterlab-variableInspector#56]
I am attempting to install this but I am encountering some issues. 

When I run:

> jupyter labextension install . 

I get:

> "jupyterlab_variableinspector@0.1.0" is not compatible with the current JupyterLab
> Conflicting Dependencies:
> JupyterLab              Extension        Package
> >=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/application
> >=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/apputils
> >=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/console
> >=0.19.1 <0.20.0        >=0.18.0 <0.19.0 @jupyterlab/notebook

The results of:

> jupyter lab --version

Is:

> 0.35.0

The full output with debug is below:

>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 77, in start
>     ans = self.run_task()
> 
>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in run_task
>     for arg in self.extra_args
> 
>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
>     for arg in self.extra_args
> 
>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 219, in install_extension
>     return handler.install_extension(extension)
> 
>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 418, in install_extension
>     info = self._install_extension(extension, tempdir)
> 
>   File "/usr/local/lib/python3.7/site-packages/jupyterlab/commands.py", line 1293, in _install_extension
>     raise ValueError(msg)

I did some poking around and it appears that my staging json file may have the wrong version in it? I am not sure what this is or how to fix.

File path:

> /usr/local/lib/python3.7/site-packages/jupyterlab/staging/package.json

File contents below:

> {
>   "name": "@jupyterlab/application-top",
>   "version": "0.19.1",
>   "private": true,
>   "scripts": {
>     "build": "webpack",
>     "build:prod": "webpack --config webpack.prod.config.js",
>     "build:prod:stats": "webpack --profile --config webpack.prod.config.js --json > stats.json",
>     "build:stats": "webpack --profile --json > stats.json",
>     "clean": "rimraf build",
>     "prepublishOnly": "npm run build",
>     "watch": "webpack --watch"
>   },
>   "dependencies": {
>     "@jupyterlab/application": "^0.19.1",
>     "@jupyterlab/application-extension": "^0.19.1",
>     "@jupyterlab/apputils": "^0.19.1",
>     "@jupyterlab/apputils-extension": "^0.19.1",
>     "@jupyterlab/attachments": "^0.19.1",
>     "@jupyterlab/cells": "^0.19.1",
>     "@jupyterlab/codeeditor": "^0.19.1",
>     "@jupyterlab/codemirror": "^0.19.1",
>     "@jupyterlab/codemirror-extension": "^0.19.1",
>     "@jupyterlab/completer": "^0.19.1",
>     "@jupyterlab/completer-extension": "^0.19.1",
>     "@jupyterlab/console": "^0.19.1",
>     "@jupyterlab/console-extension": "^0.19.1",
>     "@jupyterlab/coreutils": "^2.2.1",
>     "@jupyterlab/csvviewer": "^0.19.1",
>     "@jupyterlab/csvviewer-extension": "^0.19.1",
>     "@jupyterlab/docmanager": "^0.19.1",
>     "@jupyterlab/docmanager-extension": "^0.19.1",
>     "@jupyterlab/docregistry": "^0.19.1",
>     "@jupyterlab/extensionmanager": "^0.19.1",
>     "@jupyterlab/extensionmanager-extension": "^0.19.1",
>     "@jupyterlab/faq-extension": "^0.19.1",
>     "@jupyterlab/filebrowser": "^0.19.1",
>     "@jupyterlab/filebrowser-extension": "^0.19.1",
>     "@jupyterlab/fileeditor": "^0.19.1",
>     "@jupyterlab/fileeditor-extension": "^0.19.1",
>     "@jupyterlab/help-extension": "^0.19.1",
>     "@jupyterlab/imageviewer": "^0.19.1",
>     "@jupyterlab/imageviewer-extension": "^0.19.1",
>     "@jupyterlab/inspector": "^0.19.1",
>     "@jupyterlab/inspector-extension": "^0.19.1",
>     "@jupyterlab/javascript-extension": "^0.19.1",
>     "@jupyterlab/json-extension": "^0.18.1",
>     "@jupyterlab/launcher": "^0.19.1",
>     "@jupyterlab/launcher-extension": "^0.19.1",
>     "@jupyterlab/mainmenu": "^0.8.1",
>     "@jupyterlab/mainmenu-extension": "^0.8.1",
>     "@jupyterlab/markdownviewer-extension": "^0.19.1",
>     "@jupyterlab/mathjax2": "^0.7.1",
>     "@jupyterlab/mathjax2-extension": "^0.7.1",
>     "@jupyterlab/notebook": "^0.19.1",
>     "@jupyterlab/notebook-extension": "^0.19.1",
>     "@jupyterlab/observables": "^2.1.1",
>     "@jupyterlab/outputarea": "^0.19.1",
>     "@jupyterlab/pdf-extension": "^0.10.1",
>     "@jupyterlab/rendermime": "^0.19.1",
>     "@jupyterlab/rendermime-extension": "^0.13.1",
>     "@jupyterlab/rendermime-interfaces": "^1.2.1",
>     "@jupyterlab/running": "^0.19.1",
>     "@jupyterlab/running-extension": "^0.19.1",
>     "@jupyterlab/services": "^3.2.1",
>     "@jupyterlab/settingeditor": "^0.8.1",
>     "@jupyterlab/settingeditor-extension": "^0.14.1",
>     "@jupyterlab/shortcuts-extension": "^0.19.1",
>     "@jupyterlab/tabmanager-extension": "^0.19.1",
>     "@jupyterlab/terminal": "^0.19.1",
>     "@jupyterlab/terminal-extension": "^0.19.1",
>     "@jupyterlab/theme-dark-extension": "^0.19.1",
>     "@jupyterlab/theme-light-extension": "^0.19.1",
>     "@jupyterlab/tooltip": "^0.19.1",
>     "@jupyterlab/tooltip-extension": "^0.19.1",
>     "@jupyterlab/vdom-extension": "^0.18.1",
>     "@jupyterlab/vega4-extension": "^0.18.1",
>     "@phosphor/algorithm": "^1.1.2",
>     "@phosphor/application": "^1.6.0",
>     "@phosphor/commands": "^1.6.1",
>     "@phosphor/coreutils": "^1.3.0",
>     "@phosphor/datagrid": "^0.1.6",
>     "@phosphor/disposable": "^1.1.2",
>     "@phosphor/domutils": "^1.1.2",
>     "@phosphor/dragdrop": "^1.3.0",
>     "@phosphor/messaging": "^1.2.2",
>     "@phosphor/properties": "^1.1.2",
>     "@phosphor/signaling": "^1.2.2",
>     "@phosphor/virtualdom": "^1.1.2",
>     "@phosphor/widgets": "^1.6.0",
>     "ajv": "~5.1.6",
>     "ansi_up": "^3.0.0",
>     "codemirror": "~5.39.0",
>     "comment-json": "^1.1.3",
>     "es6-promise": "~4.1.1",
>     "marked": "~0.4.0",
>     "moment": "~2.21.0",
>     "path-posix": "~1.0.0",
>     "react": "~16.4.2",
>     "react-dom": "~16.4.2",
>     "react-paginate": "^5.2.3",
>     "sanitize-html": "~1.18.2",
>     "semver": "^5.5.0",
>     "url-parse": "~1.4.3",
>     "xterm": "~3.3.0"
>   },
>   "devDependencies": {
>     "@jupyterlab/buildutils": "^0.11.1",
>     "css-loader": "~0.28.7",
>     "duplicate-package-checker-webpack-plugin": "^3.0.0",
>     "file-loader": "~1.1.11",
>     "fs-extra": "~4.0.2",
>     "glob": "~7.1.2",
>     "handlebars": "~4.0.11",
>     "html-loader": "^0.5.1",
>     "html-webpack-plugin": "~3.2.0",
>     "raw-loader": "~0.5.1",
>     "rimraf": "~2.6.2",
>     "sort-package-json": "~1.7.1",
>     "source-map-loader": "~0.2.1",
>     "style-loader": "~0.21.0",
>     "uglifyjs-webpack-plugin": "~1.2.5",
>     "url-loader": "~1.0.1",
>     "webpack": "~4.12.0",
>     "webpack-cli": "^3.0.3",
>     "webpack-merge": "^4.1.1"
>   },
>   "engines": {
>     "node": ">=6.11.5"
>   },
>   "jupyterlab": {
>     "extensions": {
>       "@jupyterlab/application-extension": "",
>       "@jupyterlab/apputils-extension": "",
>       "@jupyterlab/codemirror-extension": "",
>       "@jupyterlab/completer-extension": "",
>       "@jupyterlab/console-extension": "",
>       "@jupyterlab/csvviewer-extension": "",
>       "@jupyterlab/docmanager-extension": "",
>       "@jupyterlab/extensionmanager-extension": "",
>       "@jupyterlab/faq-extension": "",
>       "@jupyterlab/filebrowser-extension": "",
>       "@jupyterlab/fileeditor-extension": "",
>       "@jupyterlab/help-extension": "",
>       "@jupyterlab/imageviewer-extension": "",
>       "@jupyterlab/inspector-extension": "",
>       "@jupyterlab/launcher-extension": "",
>       "@jupyterlab/mainmenu-extension": "",
>       "@jupyterlab/mathjax2-extension": "",
>       "@jupyterlab/notebook-extension": "",
>       "@jupyterlab/rendermime-extension": "",
>       "@jupyterlab/running-extension": "",
>       "@jupyterlab/settingeditor-extension": "",
>       "@jupyterlab/shortcuts-extension": "",
>       "@jupyterlab/tabmanager-extension": "",
>       "@jupyterlab/terminal-extension": "",
>       "@jupyterlab/theme-dark-extension": "",
>       "@jupyterlab/theme-light-extension": "",
>       "@jupyterlab/tooltip-extension": ""
>     },
>     "mimeExtensions": {
>       "@jupyterlab/javascript-extension": "",
>       "@jupyterlab/json-extension": "",
>       "@jupyterlab/markdownviewer-extension": "",
>       "@jupyterlab/pdf-extension": "",
>       "@jupyterlab/vdom-extension": "",
>       "@jupyterlab/vega4-extension": ""
>     },
>     "name": "JupyterLab",
>     "buildDir": "./build",
>     "outputDir": "..",
>     "singletonPackages": [
>       "@jupyterlab/application",
>       "@jupyterlab/apputils",
>       "@jupyterlab/console",
>       "@jupyterlab/coreutils",
>       "@jupyterlab/docmanager",
>       "@jupyterlab/extensionmanager",
>       "@jupyterlab/filebrowser",
>       "@jupyterlab/fileeditor",
>       "@jupyterlab/imageviewer",
>       "@jupyterlab/launcher",
>       "@jupyterlab/notebook",
>       "@jupyterlab/rendermime",
>       "@jupyterlab/rendermime-interfaces",
>       "@jupyterlab/services",
>       "@jupyterlab/terminal",
>       "@jupyterlab/tooltip",
>       "@phosphor/coreutils",
>       "@phosphor/widgets"
>     ],
>     "vendor": [
>       "@phosphor/algorithm",
>       "@phosphor/application",
>       "@phosphor/commands",
>       "@phosphor/coreutils",
>       "@phosphor/datagrid",
>       "@phosphor/disposable",
>       "@phosphor/domutils",
>       "@phosphor/dragdrop",
>       "@phosphor/messaging",
>       "@phosphor/properties",
>       "@phosphor/signaling",
>       "@phosphor/virtualdom",
>       "@phosphor/widgets",
>       "ajv",
>       "ansi_up",
>       "codemirror",
>       "comment-json",
>       "es6-promise",
>       "marked",
>       "moment",
>       "path-posix",
>       "react",
>       "react-dom",
>       "react-paginate",
>       "sanitize-html",
>       "semver",
>       "url-parse",
>       "xterm"
>     ],
>     "version": "0.35.0",
>     "linkedPackages": {},
>     "staticDir": "../static"
>   }
> }
> 

Any assistance would be great. I have already tried:

- pip install jupyterlab (again)

MacOS High Sierra Version 10.13.6

**Comment by lckr** [comment]
This is due to a new release of jupyterlab. I will update the corresponding packages.

**Comment by lckr** [comment]
I updated the requirement s.t. the inspector should work with jupyterlab 0.35 now. If this doesn't resolve your issue, please reopen it.

**Comment by ajscriv** [comment]
@lckr  Fantastic stuff - that worked! Thanks

**Comment by fheday** [comment]
Unfortunately, doesn't work with JupyterLab v0.35.4

**Comment by nathanielatom** [comment]
@fheday It does seem to work with JupyterLab v0.35.4 now.

**Comment by Hotsuyuki** [comment]
When my jupyterlab version was v0.34.9, it occurred same error as @ajscriv .
But when I updated (reinstalled) jupyterlab to v0.35.4, it worked successfully.

```
$ pip uninstall jupyterlab # jupyterlab was v0.34.9 at that time
$ pip install --upgrade pip # pip is now v19.0.3
$ pip isntall jupyterlab # now jupyterlab is v0.35.4
$ jupyter labextension install @lckr/jupyterlab_variableinspector # now worked well ;-)
```
