### ISSUE TITLE
Cannot get matrix view to open

### ISSUE THREAD

**Issue by koenlek** [lckr/jupyterlab-variableInspector#60]
I tried opening the matrix view but nothing happens. From the demo in the README, it seems like I should just left-click the np array data in the "content" column. If I do that, nothing happens. I tried this for both python2 and python3 kernels, using this simple cell of code:

```py
import numpy as np
matrix = np.random.randn(10,10)
```

I don't see any errors in the terminal in which I started jupyter lab.

Screenshot:
![image](https://user-images.githubusercontent.com/6514289/46863322-680c3400-ce17-11e8-9fb9-95a2217ef2ea.png)

Using Ubuntu 16.04, Firefox 62, jupyter lab 0.35.0, and latest master from this repo build with nodejs 10.12. Also tried with Chrome 69.

By the way: great work on this plugin! I really believe it adds great value to Jupyter! Hopefully it will evolve into a rich variable inspector like we know from Matlab :)

**Comment by FrancisBase** [comment]
Hi, after installing everything it displays column headers in blank matrix although values were assigned to variables. regards thanks in advance

**Comment by FrancisBase** [comment]
![untitled](https://user-images.githubusercontent.com/24868420/47154237-a99a5480-d2d9-11e8-9c1d-539da0bab069.png)

**Comment by FrancisBase** [comment]
It's working! only required to do was refresh by right clicking in Variable Inspector window and reload contents accordingly. Cheers!

**Comment by koenlek** [comment]
Works! It turned that you need to install both pandas and numpy to get it to work. I thought installing numpy (without pandas) would be enough for showing matrix view for numpy, but it itsn't. It will only work if both are installed. Also, for python2 kernel you'll need pandas/numpy for python2, and for python3 you need them for python3. E.g. install like this:

```
sudo -H python2 -m pip install numpy pandas
sudo -H python3 -m pip install numpy pandas
```

**Comment by sho-87** [comment]
this still feels like buggy behaviour. seems like a big ask to require pandas in a situation like this. is there something about the implementation that requires pandas as a dependency for even non-df objects...?

**Comment by dstanner** [comment]
I am having issues with this. I click in the contents field of the dataframe I want to inspect, and nothing happens. 

I tried the above suggestion of right clicking and re-loading and nothing happened, either.

Any suggestions?

MacOS 10.12.6
Python 3.6
JupyterLab 0.35.0
Pandas 0.23.0
NumPy 1.14.3

**Comment by gi3265** [comment]
> I am having issues with this. I click in the contents field of the dataframe I want to inspect, and nothing happens.
> 
> I tried the above suggestion of right clicking and re-loading and nothing happened, either.
> 
> Any suggestions?
> 
> MacOS 10.12.6
> Python 3.6
> JupyterLab 0.35.0
> Pandas 0.23.0
> NumPy 1.14.3

you should write 'import pandas as pd' literally in code!
I had the same problem with you but soon after i import pandas and click 'view contents' it worked just fine.
hope it helps
