### ISSUE TITLE
Error while inspecting NetworkX objects

### ISSUE THREAD

**Issue by carlosnatalino** [lckr/jupyterlab-variableInspector#68]
I am facing an issue when using this plugin and using NetworkX Graph objects. While I'm not using any nx.Graph object, the plugin works fine, as in the screen below:

![screen shot 2018-11-28 at 09 50 21](https://user-images.githubusercontent.com/6130746/49152763-1f9bcd80-f314-11e8-8fef-ab0e3e201a55.png)

Once I create an nx.Graph object, I'm having the problem as in the image below, and from that point the plugin stops working.

![screen shot 2018-11-28 at 09 50 50](https://user-images.githubusercontent.com/6130746/49152807-3fcb8c80-f314-11e8-9a98-2c7bdd99c9cb.png)

I have tracked the issue to the file inspectorscripts.ts, line 127, `if str(obj)[0] == "<"`, where converting nx.Graph to strings does not return any character, which causes the problem while checking the first character of the string.

I have fixed my own code by including a `if len(str(obj)) > 0` before the `if str(obj)[0] == "<"`, which has solved my problem so far. Now, I am getting the following screen when using nx.Graph objects:

![screen shot 2018-11-28 at 10 08 33](https://user-images.githubusercontent.com/6130746/49153070-f3348100-f314-11e8-82aa-1bfe51868fd7.png)

Please let me know if this solution is the correct one, or if I should do something else. Please also consider including this fix in the next release. The tool is great, I'm using it a lot and suggesting it to my colleagues!

Thanks! Carlos

**Comment by chappers** [comment]
My take is this functionality is probably related to how it might be implemented for #33 - don't think its appropriate to fix it "as is"
