### ISSUE TITLE
Install from github raises ValueError: Missing extension module "lib/index.js"

### ISSUE THREAD

**Issue by nathanielatom** [lckr/jupyterlab-variableInspector#73]
I ran `jupyter labextension install --debug https://github.com/lckr/jupyterlab-variableInspector` from the README. 

Full Output:
```
Node v11.6.0

> /usr/local/bin/npm pack https://github.com/lckr/jupyterlab-variableInspector
npm notice 
npm notice 📦  jupyterlab_variableinspector@0.1.0
npm notice === Tarball Contents === 
npm notice 1.3kB package.json   
npm notice 1.1kB LICENSE        
npm notice 2.0kB README.md      
npm notice 1.0kB style/index.css
npm notice === Tarball Details === 
npm notice name:          jupyterlab_variableinspector            
npm notice version:       0.1.0                                   
npm notice filename:      jupyterlab_variableinspector-0.1.0.tgz  
npm notice package size:  2.5 kB                                  
npm notice unpacked size: 5.4 kB                                  
npm notice shasum:        05f2583b9a63807433b8560adcedd0c13a4bf5f9
npm notice integrity:     sha512-S+NLW6MVDJWFK[...]7q5qXKqi91Ibg==
npm notice total files:   4                                       
npm notice 
jupyterlab_variableinspector-0.1.0.tgz
Traceback (most recent call last):

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 77, in start
    ans = self.run_task()

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in run_task
    for arg in self.extra_args

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/labextensions.py", line 106, in <listcomp>
    for arg in self.extra_args

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 219, in install_extension
    return handler.install_extension(extension)

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 418, in install_extension
    info = self._install_extension(extension, tempdir)

  File "/Users/Atom/.miniconda/lib/python3.7/site-packages/jupyterlab/commands.py", line 1257, in _install_extension
    raise ValueError(msg % (extension, '\n'.join(messages)))

ValueError: "https://github.com/lckr/jupyterlab-variableInspector" is not a valid extension:
Missing extension module "lib/index.js"


Errored, use --debug for full output:
ValueError: "https://github.com/lckr/jupyterlab-variableInspector" is not a valid extension:
Missing extension module "lib/index.js"
```

I noticed the repo has no `lib/index.js` but it does have `src/index.ts`, could it be as simple as changing the path to this file in `package.json`?

**Comment by nathanielatom** [comment]
Cloning the repo and installing locally works. But I'd like to use jupyterlab (along with this extension) for education purposes, so the one-line install from github would still be very useful.

Thanks for making such a great extension! It run beautifully with JupyterLab v0.35.4. 
<img width="1434" alt="screenshot 2019-01-17 20 39 44" src="https://user-images.githubusercontent.com/3137319/51360280-06eca000-1a99-11e9-9370-b7718dc5d60c.png">

**Comment by chappers** [comment]
Hi,

We'll address it in due time, considering the extension hasn't even hit a beta release yet I don't think you should be relying on it on a production environment?

**Comment by chappers** [comment]
It looks like its similar to the issue here: https://github.com/jupyterlab/jupyterlab/issues/5852 and maybe this one https://github.com/jupyterlab/jupyter-renderers/issues/132

I will investigate when I have time...

**Comment by memory-yancy** [comment]
@chappers Thank you for your work ! 
> We'll address it in due time, considering the extension hasn't even hit a beta release yet I don't think you should be relying on it on a production environment?

OK, I see ! But, maybe I'm looking forward to your good news about release version

**Comment by naefl** [comment]
Trying to run this from a miniconda3 based Dockerfile gives me the same error, while doing it on my local machine doesn't produce an error. 

Same goes with building it locally, build from Dockerfile produces an error, from my local machine.

Aware this isn't beta stage but incredibly useful, so don't want to forego it.

**Comment by lckr** [comment]
Hey all,
I just published the current version of this extension on npm and verified that the installation works for me. Additonally, I updated the readme to reflect the new installation guidelines.

Please try installing it with `jupyter labextension install @lckr/jupyterlab_variableinspector` and let me know if that works for you.

Best, lckr

**Comment by nathanielatom** [comment]
Hi @lckr, it works great! Thanks!
