### ISSUE TITLE
Problem with R big dataframe

### ISSUE THREAD

**Issue by muharif** [lckr/jupyterlab-variableInspector#75]
Hi,

Really appreciate your time on making this extension. I have one small issue that you can probably helped to fix it easily. Sometimes I have to load huge dataframe with the R kernel on jupyterlab and I found that the inspector printed all the dataframe content. Is it possible to format it the same way as loading df in Python? Or is there anyway to disable temporarily the content column?

Thanks!!!

![image](https://user-images.githubusercontent.com/856024/53402694-816ee080-39b2-11e9-8f6c-6839f4966aea.png)

**Comment by M3nt3** [comment]
Hi,

The same problem happens with Python 3.0: the variable inspector is trying to display huge dataframes, and it may even lag/crash the kernel while doing this.
It would be wonderful if the extension could just display a snippet for large datasets, or allow one to disable the display of contents.

anyway, wonderful job, thanks!

**Comment by muharif** [comment]
I think with Python, they do a perfect job since they will only print the first 150 characters of the column names. Not sure if I'm reproducing your problem.

![image](https://user-images.githubusercontent.com/856024/53564489-570a5800-3b57-11e9-9a31-6f86c7ccbf18.png)

**Comment by lckr** [comment]
Similar behavior to python will be achieved once #83 is merged.
