### ISSUE TITLE
Unicode in dataframes

### ISSUE THREAD

**Issue by wj-c** [lckr/jupyterlab-variableInspector#77]
Unicode content in variables panel shows fine now #63.

But if there are unicode characters within a dataframe, they still won't show properly. 

![image](https://user-images.githubusercontent.com/35519780/53737548-ce2d4c80-3ec7-11e9-8f84-1437d23d867e.png)

**Comment by blacktea-latte** [comment]
I can confirm this issue. Data pulled that contains foregin characters (UTF8 encoding) displayed ok in the notebook but variable inspector would display the same thing in gibberish.

**Comment by lckr** [comment]
Should be fixed with #84. Please confirm ;-)
