### ISSUE TITLE
Show array contents in matrix form only shows index

### ISSUE THREAD

**Issue by andreas-h** [lckr/jupyterlab-variableInspector#78]
I installed variableinspector using

    jupyter labextension install @lckr/jupyterlab_variableinspector

And it seems like it installed okay:

    @lamoslab [~] cndjph jupyter labextension list
    JupyterLab v0.35.4
    Known labextensions:
       app dir: /home/jupyterhub/conda/envs/prod/share/jupyter/lab
            @jupyter-widgets/jupyterlab-manager v0.38.1  enabled  OK
            @jupyterlab/git v0.5.0  enabled  OK
            @jupyterlab/hub-extension v0.12.0  enabled  OK
            @jupyterlab/toc v0.6.0  enabled  OK
            @lckr/jupyterlab_variableinspector v0.1.0  enabled  OK
            beakerx-jupyterlab v1.3.0  enabled  OK
            nbdime-jupyterlab v0.6.0  enabled  OK

When in JupyterLab I run

    import numpy as np
    a = np.random.randn(100).reshape((10, 10))

I do see the array `a` in the variable inspector.

However, when I now click on the "Content" of the array in varableinspector, a new "window" pops up, looking something like this:

    index
    0
    1
    2
    3
    4
    5
    6
    7
    8
    9

Any idea what's going on here?

**Comment by lckr** [comment]
Hey,
Sorry for the late reply. I tried to reproduce this, but for me it works as expected. Can you make sure that you have numpy and pandas correctly installed?
