### ISSUE TITLE
installing extension causes kernel to get stuck restarting

### ISSUE THREAD

**Issue by kaiaeberli** [lckr/jupyterlab-variableInspector#79]
Installing this extension for jupyterlab 0.35.3 causes the Kernel get stuck in "restarting" mode (circle at top right of notebook is constantly grey, saying "restarting"). This disappears if I uninstall the extension.

**Comment by lckr** [comment]
Thanks for the report, looking into it!

**Comment by sho-87** [comment]
I get the same problem on jupyter lab 0.35

**Comment by lckr** [comment]
Hey, can you give me some more information about this issue?

I tried to reproduce this with the following setup:
- fresh jupyterlab install (0.35.4) 
- inspector installation via `jupyter labextension install @lckr/jupyterlab_variableinspector` 
- python3 kernel in notebook and console
but could not experience this issue yet.

Thanks in advance.

**Comment by sho-87** [comment]
in my case it seems to be an interaction with a bad installation of tensorflow

when I have both tensorflow and variableInspector installed, my terminal shows the following error which results in the restart loop:

`check failed pybfloat16_type.tp_base = nullptr`

that is the result of a tensorflow installation error

jupyterlab works fine when I uninstall variableInspector because then nothing is trying to import tensorflow, hence no error, hence no restart loop

so I think this can be closed unless its not tensorflow related (@kaiaeberli ?)

**Comment by kaiaeberli** [comment]
@sho-87 For me it doesn't seem to be tensorflow related - at least I don't get this error message. I just tried it again, on jupyter 0.35.3, running console as "jupyter lab --debug". It does not show any error messages, but still keeps restarting the kernel over and over. Are there any specific logs i should post?

**Comment by mg3146** [comment]
Hi, I continue to have an issue when I restart the kernel.

**Comment by lckr** [comment]
I could somewhat reproduce this. I noticed that in this current case its is not the kernel that is stuck restarting but the variable inspector not reconnecting to the kernel, i.e., the kernel is still usable but the inspector does not reconnect automatically. As of now a work around is to reload the page.
Currently we're listening for a kernel message that indicates a restart event and have to investigate if this has changed in the jupyterlab 1.0 release.

**Comment by joedon4477** [comment]
I'm having the same issue with the variable inspector working at first, until you make the first restart of the kernel, then the variable inspector is stuck in "Restarting kernel..." indefinitely. As Ickr has mentioned, refreshing the entire application works, but is quite inconvenient. Has anyone found a solution to this yet? 

BTW I still like the extension Ickr so I appreciate it in general.

Using Jupyterlab version 1.2.6 

Thanks
