### ISSUE TITLE
Feature request: PyTorch Tensors

### ISSUE THREAD

**Issue by baldassarreFe** [lckr/jupyterlab-variableInspector#82]
Since PyTorch tensors are very similar to Numpy arrays, is it possible to get the same inspection features for them? Their shape in particular would be great to visualize.

I can work on this if someone can point me in the right direction. I think we just need to add some lines to [`inspectorscripts.ts`](https://github.com/lckr/jupyterlab-variableInspector/blob/ebad24fad6d421e39674c4fc9fe6b07ae0551fd4/src/inspectorscripts.ts), but is there something more?

**Comment by lckr** [comment]
Hey,
Yes, you're right – you only need to modify the python script in the `/src/inspectorscripts.ts` file.
