### ISSUE TITLE
if size of dataframe and numpy are too big, it cant be visualized

### ISSUE THREAD

**Issue by roccqqck** [lckr/jupyterlab-variableInspector#85]
if size of dataframe and numpy are too big, it cant be visualized.

![Screen Shot 2019-04-16 at 1 45 38 AM](https://user-images.githubusercontent.com/34628766/56153716-60f1f880-5fe9-11e9-9cdd-2c0c50a44d6f.png)

i can view news2,
 but not news

**Comment by sho-87** [comment]
can you open chrome dev tools and post the error that shows when you try to view the dataframe?

**Comment by roccqqck** [comment]
![Screen Shot 2019-04-24 at 2 47 02 PM](https://user-images.githubusercontent.com/34628766/56638165-f81d1700-669f-11e9-9774-9ca02fee77d1.png)

**Comment by roccqqck** [comment]
> can you open chrome dev tools and post the error that shows when you try to view the dataframe?

![Screen Shot 2019-04-24 at 2 47 02 PM](https://user-images.githubusercontent.com/34628766/56638190-0e2ad780-66a0-11e9-8c34-bce5f10bae4b.png)

**Comment by sho-87** [comment]
ah this seems to be a very similar issue to #86 

I'm guessing somewhere in your `news` dataframe you have some values that have a `'` character?

**Comment by roccqqck** [comment]
> ah this seems to be a very similar issue to #86
> 
> I'm guessing somewhere in your `news` dataframe you have some values that have a `'` character?

thanks

i use replace all```'``` and ```"```
then
it can be visualized now
```
df['column_name'] = fd['column_name'].astype(str).str.replace("'", ' ').str.replace('"', ' ')
```
