### ISSUE TITLE
Shape inconsistent between install methods

### ISSUE THREAD

**Issue by sho-87** [lckr/jupyterlab-variableInspector#89]
The readme lists 2 installation methods. When I use the first option (`jupyter labextension install @lckr/jupyterlab_variableinspector`), the variable inspector looks like this:

![option1](https://user-images.githubusercontent.com/5199715/56610647-ca16d480-65c4-11e9-8852-97acd819edef.png)

But when I clone the repo and install using option 2 it looks like this:

![option2](https://user-images.githubusercontent.com/5199715/56610668-da2eb400-65c4-11e9-9f82-32dd42ebd495.png)

Notice how the word 'DataFrame' shows up with the second option but not the first in the Shape column

Why does this happen? Are they building from different source files?

Which is the intended/desired behavior? To me, not showing the type (i.e. option 1) makes more sense as we already have a type column

**Comment by lckr** [comment]
Option 1 should now be the result regardless of installation method.
