### ISSUE TITLE
VSCode Variable Explorer

### ISSUE THREAD

**Issue by dhirschfeld** [lckr/jupyterlab-variableInspector#92]
VSCode have implemented a variable explorer / data viewer:

https://devblogs.microsoft.com/python/python-in-visual-studio-code-april-2019-release/

There might be something to learn from their implementation.

**Comment by dhirschfeld** [comment]
This isn't really an issue - just for informational purposes so feel free to close...

**Comment by sho-87** [comment]
just saw this today as well and looks very interesting. i use vscode for non-data work and starting to wonder whether it might be better to just move away from jupyterlab and use vscode for everything

does jupyterlab offer anything that vscode doesnt?

**Comment by dhirschfeld** [comment]
I think VSCode is a fantastic editor but personally find it to be pretty cumbersome for any interactive work.

The situation may well have improved recently though.

I use jupyterlab for interactive data exploration/visualisation work where the rich html output is a key benefit. [neuron](https://github.com/neuron-team/vscode-ipe) seems an interesting step in that direction, but last I checked it wasn't as functional as Atom's hydrogen and there doesn't seem to have been many commits since...
