### ISSUE TITLE
Data Explorer

### ISSUE THREAD

**Issue by dhirschfeld** [lckr/jupyterlab-variableInspector#95]
There's likely some overlap in functionality with the [JupyterLab Data Explorer](https://github.com/jupyterlab/jupyterlab-data-explorer).

It's not stable yet but it might be useful to keep an eye on that project to see if you could leverage off the work there.

**Comment by sho-87** [comment]
interesting. that looks like its being developed as part of jupyterlab core

but im wondering what their definition of 'dataset' is as it looks like its primarily aimed at working with physical files. it would be nice if variables created within kernel session could be automatically registered with the registry so extensions like this one can grab them directly. time will tell I suppose...

**Comment by lckr** [comment]
This extension looks really nice. If this is going to work with temporary in-kernel datasets, matrices, dataframes et al. I will gladly switch our current matrix viewer for the data explorer.

**Comment by saulshanabrook** [comment]
> but im wondering what their definition of 'dataset' is as it looks like its primarily aimed at working with physical files. it would be nice if variables created within kernel session could be automatically registered with the registry so extensions like this one can grab them directly.

Yeah the MVP is about describing things like CSV files or notebook outputs. But I think being able to read data from the kernel would make sense as an extension.
