### ISSUE TITLE
Failing to build with typescript@3.5.1

### ISSUE THREAD

**Issue by lucasosouza** [lckr/jupyterlab-variableInspector#96]
Was failing to build with the latest version of typescript. Error:
`race<T>(values: Iterable<T>): Promise<T extends PromiseLike<infer U> ? U : T>;`

I was able to fix it by downgrading typescript to 3.0 and rerunning npm install, in case anyone stumbles upon this issue.  

Thanks for the great tool.

**Comment by urfdvw** [comment]
same issue on miniconda win10

**Comment by sho-87** [comment]
@lckr is this fixed with the typescript version update in https://github.com/lckr/jupyterlab-variableInspector/pull/107?

**Comment by lckr** [comment]
Yes, we're now using `"typescript": "^3.5"`.
