### ISSUE TITLE
This extension does not yet support the current version of JupyterLab.

### ISSUE THREAD

**Issue by eungbean** [lckr/jupyterlab-variableInspector#99]
Extension Installation Error
An error occurred installing @lckr/jupyterlab_variableinspector.

Error message:

This extension does not yet support the current version of JupyterLab.

Conflicting Dependencies:
JupyterLab              Extension      Package
>=1.0.0 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/application
>=1.0.0 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/apputils
>=1.0.0 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/console
>=3.0.0 <4.0.0          >=2.1.4 <3.0.0 @jupyterlab/coreutils
>=1.0.0 <2.0.0          >=0.19.0 <0.20.0@jupyterlab/notebook
>=4.0.0 <5.0.0          >=3.1.4 <4.0.0 @jupyterlab/services

btw, I'm using Jupyterlab version 1.0.1.
How can I fix this problem?

**Comment by MainHanzo** [comment]
conda update jupyterlab

**Comment by Lukikay** [comment]
Got the same problem here, Jupyterlab version 1.0.1 via pip.

**Comment by ladychili** [comment]
same here 😢

**Comment by consideRatio** [comment]
It relates to whats written out in `packages.json`, and was for example updated like this when JupyterLab 0.35 was released: https://github.com/lckr/jupyterlab-variableInspector/pull/57/files

**Comment by kevmk04** [comment]
Same :-(

**Comment by polohot** [comment]
Any workaround for this? I would really love to use this function in my jupyterlab :)

**Comment by zhiyuanzhai** [comment]
Same...

**Comment by tetsuro90** [comment]
same here. I'd really like to use this extension.

**Comment by k-allika** [comment]
Same here .. JupyterLab 1.0.2. Missing this extension!

**Comment by sho-87** [comment]
I just merged in https://github.com/lckr/jupyterlab-variableInspector/pull/101 , which should fix this problem

I think we need an npm update before `jupyter labextension install @lckr/jupyterlab_variableinspector` will work, so for now you'll have to try installing by cloning the repo
